### ISSUE TITLE
Add "How I made it" documentation

### ISSUE THREAD

**Issue by emilymdubois** [emilymdubois/tmbbq-2017#1]
This application covered a few big topics:
- Initialize a React + Redux application
- Add a [Mapbox GL JS](https://www.mapbox.com/mapbox-gl-js/api/) map
- Use Mapbox GL JS [expressions](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions)
- Optimize for different screen sizes
- Build and deploy to GitHub pages

**Comment by astrowonk** [comment]
My only comment is that this is pretty cool. As a BBQ fan, a Texan, and a very noob web-app maker (just with R, shiny, and leaflet so far) this was a neat find.
